include: package:lint/analysis_options.yaml

linter:
    rules:
        non_constant_identifier_names: false
        prefer_if_elements_to_conditional_expressions: false
        avoid_print: false
        prefer_final_locals: false
        sort_unnamed_constructors_first: false
        sort_pub_dependencies: false

analyzer:
    errors:
        missing_return: error
        missing_required_param: error
